### ISSUE TITLE
Unable to run tests with Android and 1.3

### ISSUE THREAD

**Issue by cc-rock** [crittercism/dexmaker#18]
Hello,
I'm trying to use version 1.3 (from central repository) with Android and Mockito but I am getting the following error:
Caused by: java.lang.NoClassDefFoundError: com.google.dexmaker.dx.rop.type.Type

I also tried to import also dexmaker-dx 1.3 but it doesn't solve the issue because the package of the included classes is different (com.android.dx instead of com.google.dexmaker.dx).

The only way I've found to make it work is to build v1.3 manually and then include the **original-dexmaker-1.3** , dexmaker-dx-1.3 and dexmaker-mockito-1.3 jars in my project.
What's the difference between dexmaker and original-dexmaker? Is there a way to make things work by downloading jars from the central repository instead of including them manually?

**Comment by nhaarman** [comment]
I have run into the same issue.

**Comment by eldoth** [comment]
Me too.

**Comment by ened** [comment]
@dshirley ping? :-)

**Comment by gfx** [comment]
Have the same issue.

**Comment by ened** [comment]
See https://github.com/crittercism/dexmaker/pull/19.

**Comment by vaughandroid** [comment]
Same issue here. I'm seeing NoClassDefFoundErrors for classes under `com.google.dexmaker.stock` and `com.google.dexmaker.dx.rop.type`, but I'm sure there are more.

**Comment by dshirley** [comment]
I merged @ened's pull request and pushed it out as 1.4.  Please try that out.

**Comment by upelsin** [comment]
@dshirley the issue still exists.

Tried 1.4 (from the central repo) with Mockito 1.10.19, same NoClassDefFoundError.

**Comment by eldoth** [comment]
I tried with 1.4 and Mockito 1.10.19. 
The error that I got is this:
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.dx.rop.type.Type" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar"

**Comment by izumin5210** [comment]
i got the same error too :cry:

**Comment by steineron** [comment]
still reproduces on 1.4. any suggestions?

**Comment by tigerpenguin** [comment]
Same issue here. Using 1.2 works fine:
```
com.google.dexmaker:dexmaker:1.2
com.google.dexmaker:dexmaker-mockito:1.2
```

Using 1.4 causes issues:
```
com.crittercism.dexmaker:dexmaker:1.4
com.crittercism.dexmaker:dexmaker-mockito:1.4
```

Used `org.mockito:mockito-core:1.10.19` for both.

**Comment by andyp1per** [comment]
Same here. Why is this issue closed when it's clearly not fixed?

**Comment by vaughandroid** [comment]
The problem for me was missing the dexmaker-dx dependency (which is a new requirement). See this issue: https://github.com/crittercism/dexmaker/issues/22

**Comment by yogurtearl** [comment]
Yup, adding this worked for me.
```
androidTestCompile "com.crittercism.dexmaker:dexmaker-dx:1.4"
```

**Comment by hashemian** [comment]
Thanks, @yogurtearl and @vaughandroid , adding the dexmaker-dx fixed the issue for me as well.

**Comment by thuytrinh** [comment]
@yogurtearl U saved my day! :+1:

**Comment by andyp1per** [comment]
My pull request https://github.com/crittercism/dexmaker/pull/24 fixes both this and another compile issue but has had no activity. Is this package maintained anymore?
